name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: karlancelDimabayao
          outputs: dist/snake.svg

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated snake animation"
          add: "dist/snake.svg"
          default_author: github_actions
